# Generated by Django 2.2 on 2022-07-28 01:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Data',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ent_seq', models.IntegerField()),
                ('keb', models.TextField()),
                ('reb', models.TextField()),
                ('name_type', models.TextField()),
                ('trans_det', models.TextField()),
            ],
        ),
    ]
